/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SharedTokenRouteImport } from './routes/shared.$token'
import { Route as AppHistoryRouteImport } from './routes/_app/history'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppCompaniesRouteImport } from './routes/_app/companies'
import { Route as AppCalculatorsRouteImport } from './routes/_app/calculators'
import { Route as AppAccountRouteImport } from './routes/_app/account'
import { Route as AppCompaniesIndexRouteImport } from './routes/_app/companies/index'
import { Route as AppClientsIndexRouteImport } from './routes/_app/clients/index'
import { Route as AppCalculatorsIndexRouteImport } from './routes/_app/calculators/index'
import { Route as AppCompaniesNewRouteImport } from './routes/_app/companies/new'
import { Route as AppCompaniesCompanyIdRouteImport } from './routes/_app/companies/$companyId'
import { Route as AppClientsNewRouteImport } from './routes/_app/clients/new'
import { Route as AppClientsClientIdRouteImport } from './routes/_app/clients/$clientId'
import { Route as AppCalculatorsVestedBenefitsRouteImport } from './routes/_app/calculators/vested-benefits'
import { Route as AppCalculatorsTouRouteImport } from './routes/_app/calculators/tou'
import { Route as AppCalculatorsSourceTaxRouteImport } from './routes/_app/calculators/source-tax'
import { Route as AppCalculatorsRetirementRouteImport } from './routes/_app/calculators/retirement'
import { Route as AppCalculatorsPillar3aRouteImport } from './routes/_app/calculators/pillar3a'
import { Route as AppCalculatorsLppRouteImport } from './routes/_app/calculators/lpp'
import { Route as AppCalculatorsIncomeTaxRouteImport } from './routes/_app/calculators/income-tax'
import { Route as AppCalculatorsCrossBorderRouteImport } from './routes/_app/calculators/cross-border'
import { Route as AppCalculatorsCantonCompareRouteImport } from './routes/_app/calculators/canton-compare'
import { Route as AppCalculatorsAvsAiRouteImport } from './routes/_app/calculators/avs-ai'
import { Route as AppCompaniesCompanyIdEditRouteImport } from './routes/_app/companies/$companyId_.edit'
import { Route as AppClientsClientIdScenariosRouteImport } from './routes/_app/clients/$clientId_.scenarios'
import { Route as AppClientsClientIdEditRouteImport } from './routes/_app/clients/$clientId_.edit'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SharedTokenRoute = SharedTokenRouteImport.update({
  id: '/shared/$token',
  path: '/shared/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AppHistoryRoute = AppHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCompaniesRoute = AppCompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => AppRoute,
} as any)
const AppCalculatorsRoute = AppCalculatorsRouteImport.update({
  id: '/calculators',
  path: '/calculators',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountRoute = AppAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AppRoute,
} as any)
const AppCompaniesIndexRoute = AppCompaniesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppCompaniesRoute,
} as any)
const AppClientsIndexRoute = AppClientsIndexRouteImport.update({
  id: '/clients/',
  path: '/clients/',
  getParentRoute: () => AppRoute,
} as any)
const AppCalculatorsIndexRoute = AppCalculatorsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppCalculatorsRoute,
} as any)
const AppCompaniesNewRoute = AppCompaniesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppCompaniesRoute,
} as any)
const AppCompaniesCompanyIdRoute = AppCompaniesCompanyIdRouteImport.update({
  id: '/$companyId',
  path: '/$companyId',
  getParentRoute: () => AppCompaniesRoute,
} as any)
const AppClientsNewRoute = AppClientsNewRouteImport.update({
  id: '/clients/new',
  path: '/clients/new',
  getParentRoute: () => AppRoute,
} as any)
const AppClientsClientIdRoute = AppClientsClientIdRouteImport.update({
  id: '/clients/$clientId',
  path: '/clients/$clientId',
  getParentRoute: () => AppRoute,
} as any)
const AppCalculatorsVestedBenefitsRoute =
  AppCalculatorsVestedBenefitsRouteImport.update({
    id: '/vested-benefits',
    path: '/vested-benefits',
    getParentRoute: () => AppCalculatorsRoute,
  } as any)
const AppCalculatorsTouRoute = AppCalculatorsTouRouteImport.update({
  id: '/tou',
  path: '/tou',
  getParentRoute: () => AppCalculatorsRoute,
} as any)
const AppCalculatorsSourceTaxRoute = AppCalculatorsSourceTaxRouteImport.update({
  id: '/source-tax',
  path: '/source-tax',
  getParentRoute: () => AppCalculatorsRoute,
} as any)
const AppCalculatorsRetirementRoute =
  AppCalculatorsRetirementRouteImport.update({
    id: '/retirement',
    path: '/retirement',
    getParentRoute: () => AppCalculatorsRoute,
  } as any)
const AppCalculatorsPillar3aRoute = AppCalculatorsPillar3aRouteImport.update({
  id: '/pillar3a',
  path: '/pillar3a',
  getParentRoute: () => AppCalculatorsRoute,
} as any)
const AppCalculatorsLppRoute = AppCalculatorsLppRouteImport.update({
  id: '/lpp',
  path: '/lpp',
  getParentRoute: () => AppCalculatorsRoute,
} as any)
const AppCalculatorsIncomeTaxRoute = AppCalculatorsIncomeTaxRouteImport.update({
  id: '/income-tax',
  path: '/income-tax',
  getParentRoute: () => AppCalculatorsRoute,
} as any)
const AppCalculatorsCrossBorderRoute =
  AppCalculatorsCrossBorderRouteImport.update({
    id: '/cross-border',
    path: '/cross-border',
    getParentRoute: () => AppCalculatorsRoute,
  } as any)
const AppCalculatorsCantonCompareRoute =
  AppCalculatorsCantonCompareRouteImport.update({
    id: '/canton-compare',
    path: '/canton-compare',
    getParentRoute: () => AppCalculatorsRoute,
  } as any)
const AppCalculatorsAvsAiRoute = AppCalculatorsAvsAiRouteImport.update({
  id: '/avs-ai',
  path: '/avs-ai',
  getParentRoute: () => AppCalculatorsRoute,
} as any)
const AppCompaniesCompanyIdEditRoute =
  AppCompaniesCompanyIdEditRouteImport.update({
    id: '/$companyId_/edit',
    path: '/$companyId/edit',
    getParentRoute: () => AppCompaniesRoute,
  } as any)
const AppClientsClientIdScenariosRoute =
  AppClientsClientIdScenariosRouteImport.update({
    id: '/clients/$clientId_/scenarios',
    path: '/clients/$clientId/scenarios',
    getParentRoute: () => AppRoute,
  } as any)
const AppClientsClientIdEditRoute = AppClientsClientIdEditRouteImport.update({
  id: '/clients/$clientId_/edit',
  path: '/clients/$clientId/edit',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/account': typeof AppAccountRoute
  '/calculators': typeof AppCalculatorsRouteWithChildren
  '/companies': typeof AppCompaniesRouteWithChildren
  '/dashboard': typeof AppDashboardRoute
  '/history': typeof AppHistoryRoute
  '/shared/$token': typeof SharedTokenRoute
  '/calculators/avs-ai': typeof AppCalculatorsAvsAiRoute
  '/calculators/canton-compare': typeof AppCalculatorsCantonCompareRoute
  '/calculators/cross-border': typeof AppCalculatorsCrossBorderRoute
  '/calculators/income-tax': typeof AppCalculatorsIncomeTaxRoute
  '/calculators/lpp': typeof AppCalculatorsLppRoute
  '/calculators/pillar3a': typeof AppCalculatorsPillar3aRoute
  '/calculators/retirement': typeof AppCalculatorsRetirementRoute
  '/calculators/source-tax': typeof AppCalculatorsSourceTaxRoute
  '/calculators/tou': typeof AppCalculatorsTouRoute
  '/calculators/vested-benefits': typeof AppCalculatorsVestedBenefitsRoute
  '/clients/$clientId': typeof AppClientsClientIdRoute
  '/clients/new': typeof AppClientsNewRoute
  '/companies/$companyId': typeof AppCompaniesCompanyIdRoute
  '/companies/new': typeof AppCompaniesNewRoute
  '/calculators/': typeof AppCalculatorsIndexRoute
  '/clients/': typeof AppClientsIndexRoute
  '/companies/': typeof AppCompaniesIndexRoute
  '/clients/$clientId/edit': typeof AppClientsClientIdEditRoute
  '/clients/$clientId/scenarios': typeof AppClientsClientIdScenariosRoute
  '/companies/$companyId/edit': typeof AppCompaniesCompanyIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/account': typeof AppAccountRoute
  '/dashboard': typeof AppDashboardRoute
  '/history': typeof AppHistoryRoute
  '/shared/$token': typeof SharedTokenRoute
  '/calculators/avs-ai': typeof AppCalculatorsAvsAiRoute
  '/calculators/canton-compare': typeof AppCalculatorsCantonCompareRoute
  '/calculators/cross-border': typeof AppCalculatorsCrossBorderRoute
  '/calculators/income-tax': typeof AppCalculatorsIncomeTaxRoute
  '/calculators/lpp': typeof AppCalculatorsLppRoute
  '/calculators/pillar3a': typeof AppCalculatorsPillar3aRoute
  '/calculators/retirement': typeof AppCalculatorsRetirementRoute
  '/calculators/source-tax': typeof AppCalculatorsSourceTaxRoute
  '/calculators/tou': typeof AppCalculatorsTouRoute
  '/calculators/vested-benefits': typeof AppCalculatorsVestedBenefitsRoute
  '/clients/$clientId': typeof AppClientsClientIdRoute
  '/clients/new': typeof AppClientsNewRoute
  '/companies/$companyId': typeof AppCompaniesCompanyIdRoute
  '/companies/new': typeof AppCompaniesNewRoute
  '/calculators': typeof AppCalculatorsIndexRoute
  '/clients': typeof AppClientsIndexRoute
  '/companies': typeof AppCompaniesIndexRoute
  '/clients/$clientId/edit': typeof AppClientsClientIdEditRoute
  '/clients/$clientId/scenarios': typeof AppClientsClientIdScenariosRoute
  '/companies/$companyId/edit': typeof AppCompaniesCompanyIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/_app/account': typeof AppAccountRoute
  '/_app/calculators': typeof AppCalculatorsRouteWithChildren
  '/_app/companies': typeof AppCompaniesRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/history': typeof AppHistoryRoute
  '/shared/$token': typeof SharedTokenRoute
  '/_app/calculators/avs-ai': typeof AppCalculatorsAvsAiRoute
  '/_app/calculators/canton-compare': typeof AppCalculatorsCantonCompareRoute
  '/_app/calculators/cross-border': typeof AppCalculatorsCrossBorderRoute
  '/_app/calculators/income-tax': typeof AppCalculatorsIncomeTaxRoute
  '/_app/calculators/lpp': typeof AppCalculatorsLppRoute
  '/_app/calculators/pillar3a': typeof AppCalculatorsPillar3aRoute
  '/_app/calculators/retirement': typeof AppCalculatorsRetirementRoute
  '/_app/calculators/source-tax': typeof AppCalculatorsSourceTaxRoute
  '/_app/calculators/tou': typeof AppCalculatorsTouRoute
  '/_app/calculators/vested-benefits': typeof AppCalculatorsVestedBenefitsRoute
  '/_app/clients/$clientId': typeof AppClientsClientIdRoute
  '/_app/clients/new': typeof AppClientsNewRoute
  '/_app/companies/$companyId': typeof AppCompaniesCompanyIdRoute
  '/_app/companies/new': typeof AppCompaniesNewRoute
  '/_app/calculators/': typeof AppCalculatorsIndexRoute
  '/_app/clients/': typeof AppClientsIndexRoute
  '/_app/companies/': typeof AppCompaniesIndexRoute
  '/_app/clients/$clientId_/edit': typeof AppClientsClientIdEditRoute
  '/_app/clients/$clientId_/scenarios': typeof AppClientsClientIdScenariosRoute
  '/_app/companies/$companyId_/edit': typeof AppCompaniesCompanyIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/account'
    | '/calculators'
    | '/companies'
    | '/dashboard'
    | '/history'
    | '/shared/$token'
    | '/calculators/avs-ai'
    | '/calculators/canton-compare'
    | '/calculators/cross-border'
    | '/calculators/income-tax'
    | '/calculators/lpp'
    | '/calculators/pillar3a'
    | '/calculators/retirement'
    | '/calculators/source-tax'
    | '/calculators/tou'
    | '/calculators/vested-benefits'
    | '/clients/$clientId'
    | '/clients/new'
    | '/companies/$companyId'
    | '/companies/new'
    | '/calculators/'
    | '/clients/'
    | '/companies/'
    | '/clients/$clientId/edit'
    | '/clients/$clientId/scenarios'
    | '/companies/$companyId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/account'
    | '/dashboard'
    | '/history'
    | '/shared/$token'
    | '/calculators/avs-ai'
    | '/calculators/canton-compare'
    | '/calculators/cross-border'
    | '/calculators/income-tax'
    | '/calculators/lpp'
    | '/calculators/pillar3a'
    | '/calculators/retirement'
    | '/calculators/source-tax'
    | '/calculators/tou'
    | '/calculators/vested-benefits'
    | '/clients/$clientId'
    | '/clients/new'
    | '/companies/$companyId'
    | '/companies/new'
    | '/calculators'
    | '/clients'
    | '/companies'
    | '/clients/$clientId/edit'
    | '/clients/$clientId/scenarios'
    | '/companies/$companyId/edit'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/auth'
    | '/_app/account'
    | '/_app/calculators'
    | '/_app/companies'
    | '/_app/dashboard'
    | '/_app/history'
    | '/shared/$token'
    | '/_app/calculators/avs-ai'
    | '/_app/calculators/canton-compare'
    | '/_app/calculators/cross-border'
    | '/_app/calculators/income-tax'
    | '/_app/calculators/lpp'
    | '/_app/calculators/pillar3a'
    | '/_app/calculators/retirement'
    | '/_app/calculators/source-tax'
    | '/_app/calculators/tou'
    | '/_app/calculators/vested-benefits'
    | '/_app/clients/$clientId'
    | '/_app/clients/new'
    | '/_app/companies/$companyId'
    | '/_app/companies/new'
    | '/_app/calculators/'
    | '/_app/clients/'
    | '/_app/companies/'
    | '/_app/clients/$clientId_/edit'
    | '/_app/clients/$clientId_/scenarios'
    | '/_app/companies/$companyId_/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  SharedTokenRoute: typeof SharedTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shared/$token': {
      id: '/shared/$token'
      path: '/shared/$token'
      fullPath: '/shared/$token'
      preLoaderRoute: typeof SharedTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/history': {
      id: '/_app/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AppHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/companies': {
      id: '/_app/companies'
      path: '/companies'
      fullPath: '/companies'
      preLoaderRoute: typeof AppCompaniesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/calculators': {
      id: '/_app/calculators'
      path: '/calculators'
      fullPath: '/calculators'
      preLoaderRoute: typeof AppCalculatorsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/account': {
      id: '/_app/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AppAccountRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/companies/': {
      id: '/_app/companies/'
      path: '/'
      fullPath: '/companies/'
      preLoaderRoute: typeof AppCompaniesIndexRouteImport
      parentRoute: typeof AppCompaniesRoute
    }
    '/_app/clients/': {
      id: '/_app/clients/'
      path: '/clients'
      fullPath: '/clients/'
      preLoaderRoute: typeof AppClientsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/calculators/': {
      id: '/_app/calculators/'
      path: '/'
      fullPath: '/calculators/'
      preLoaderRoute: typeof AppCalculatorsIndexRouteImport
      parentRoute: typeof AppCalculatorsRoute
    }
    '/_app/companies/new': {
      id: '/_app/companies/new'
      path: '/new'
      fullPath: '/companies/new'
      preLoaderRoute: typeof AppCompaniesNewRouteImport
      parentRoute: typeof AppCompaniesRoute
    }
    '/_app/companies/$companyId': {
      id: '/_app/companies/$companyId'
      path: '/$companyId'
      fullPath: '/companies/$companyId'
      preLoaderRoute: typeof AppCompaniesCompanyIdRouteImport
      parentRoute: typeof AppCompaniesRoute
    }
    '/_app/clients/new': {
      id: '/_app/clients/new'
      path: '/clients/new'
      fullPath: '/clients/new'
      preLoaderRoute: typeof AppClientsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clients/$clientId': {
      id: '/_app/clients/$clientId'
      path: '/clients/$clientId'
      fullPath: '/clients/$clientId'
      preLoaderRoute: typeof AppClientsClientIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/calculators/vested-benefits': {
      id: '/_app/calculators/vested-benefits'
      path: '/vested-benefits'
      fullPath: '/calculators/vested-benefits'
      preLoaderRoute: typeof AppCalculatorsVestedBenefitsRouteImport
      parentRoute: typeof AppCalculatorsRoute
    }
    '/_app/calculators/tou': {
      id: '/_app/calculators/tou'
      path: '/tou'
      fullPath: '/calculators/tou'
      preLoaderRoute: typeof AppCalculatorsTouRouteImport
      parentRoute: typeof AppCalculatorsRoute
    }
    '/_app/calculators/source-tax': {
      id: '/_app/calculators/source-tax'
      path: '/source-tax'
      fullPath: '/calculators/source-tax'
      preLoaderRoute: typeof AppCalculatorsSourceTaxRouteImport
      parentRoute: typeof AppCalculatorsRoute
    }
    '/_app/calculators/retirement': {
      id: '/_app/calculators/retirement'
      path: '/retirement'
      fullPath: '/calculators/retirement'
      preLoaderRoute: typeof AppCalculatorsRetirementRouteImport
      parentRoute: typeof AppCalculatorsRoute
    }
    '/_app/calculators/pillar3a': {
      id: '/_app/calculators/pillar3a'
      path: '/pillar3a'
      fullPath: '/calculators/pillar3a'
      preLoaderRoute: typeof AppCalculatorsPillar3aRouteImport
      parentRoute: typeof AppCalculatorsRoute
    }
    '/_app/calculators/lpp': {
      id: '/_app/calculators/lpp'
      path: '/lpp'
      fullPath: '/calculators/lpp'
      preLoaderRoute: typeof AppCalculatorsLppRouteImport
      parentRoute: typeof AppCalculatorsRoute
    }
    '/_app/calculators/income-tax': {
      id: '/_app/calculators/income-tax'
      path: '/income-tax'
      fullPath: '/calculators/income-tax'
      preLoaderRoute: typeof AppCalculatorsIncomeTaxRouteImport
      parentRoute: typeof AppCalculatorsRoute
    }
    '/_app/calculators/cross-border': {
      id: '/_app/calculators/cross-border'
      path: '/cross-border'
      fullPath: '/calculators/cross-border'
      preLoaderRoute: typeof AppCalculatorsCrossBorderRouteImport
      parentRoute: typeof AppCalculatorsRoute
    }
    '/_app/calculators/canton-compare': {
      id: '/_app/calculators/canton-compare'
      path: '/canton-compare'
      fullPath: '/calculators/canton-compare'
      preLoaderRoute: typeof AppCalculatorsCantonCompareRouteImport
      parentRoute: typeof AppCalculatorsRoute
    }
    '/_app/calculators/avs-ai': {
      id: '/_app/calculators/avs-ai'
      path: '/avs-ai'
      fullPath: '/calculators/avs-ai'
      preLoaderRoute: typeof AppCalculatorsAvsAiRouteImport
      parentRoute: typeof AppCalculatorsRoute
    }
    '/_app/companies/$companyId_/edit': {
      id: '/_app/companies/$companyId_/edit'
      path: '/$companyId/edit'
      fullPath: '/companies/$companyId/edit'
      preLoaderRoute: typeof AppCompaniesCompanyIdEditRouteImport
      parentRoute: typeof AppCompaniesRoute
    }
    '/_app/clients/$clientId_/scenarios': {
      id: '/_app/clients/$clientId_/scenarios'
      path: '/clients/$clientId/scenarios'
      fullPath: '/clients/$clientId/scenarios'
      preLoaderRoute: typeof AppClientsClientIdScenariosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clients/$clientId_/edit': {
      id: '/_app/clients/$clientId_/edit'
      path: '/clients/$clientId/edit'
      fullPath: '/clients/$clientId/edit'
      preLoaderRoute: typeof AppClientsClientIdEditRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppCalculatorsRouteChildren {
  AppCalculatorsAvsAiRoute: typeof AppCalculatorsAvsAiRoute
  AppCalculatorsCantonCompareRoute: typeof AppCalculatorsCantonCompareRoute
  AppCalculatorsCrossBorderRoute: typeof AppCalculatorsCrossBorderRoute
  AppCalculatorsIncomeTaxRoute: typeof AppCalculatorsIncomeTaxRoute
  AppCalculatorsLppRoute: typeof AppCalculatorsLppRoute
  AppCalculatorsPillar3aRoute: typeof AppCalculatorsPillar3aRoute
  AppCalculatorsRetirementRoute: typeof AppCalculatorsRetirementRoute
  AppCalculatorsSourceTaxRoute: typeof AppCalculatorsSourceTaxRoute
  AppCalculatorsTouRoute: typeof AppCalculatorsTouRoute
  AppCalculatorsVestedBenefitsRoute: typeof AppCalculatorsVestedBenefitsRoute
  AppCalculatorsIndexRoute: typeof AppCalculatorsIndexRoute
}

const AppCalculatorsRouteChildren: AppCalculatorsRouteChildren = {
  AppCalculatorsAvsAiRoute: AppCalculatorsAvsAiRoute,
  AppCalculatorsCantonCompareRoute: AppCalculatorsCantonCompareRoute,
  AppCalculatorsCrossBorderRoute: AppCalculatorsCrossBorderRoute,
  AppCalculatorsIncomeTaxRoute: AppCalculatorsIncomeTaxRoute,
  AppCalculatorsLppRoute: AppCalculatorsLppRoute,
  AppCalculatorsPillar3aRoute: AppCalculatorsPillar3aRoute,
  AppCalculatorsRetirementRoute: AppCalculatorsRetirementRoute,
  AppCalculatorsSourceTaxRoute: AppCalculatorsSourceTaxRoute,
  AppCalculatorsTouRoute: AppCalculatorsTouRoute,
  AppCalculatorsVestedBenefitsRoute: AppCalculatorsVestedBenefitsRoute,
  AppCalculatorsIndexRoute: AppCalculatorsIndexRoute,
}

const AppCalculatorsRouteWithChildren = AppCalculatorsRoute._addFileChildren(
  AppCalculatorsRouteChildren,
)

interface AppCompaniesRouteChildren {
  AppCompaniesCompanyIdRoute: typeof AppCompaniesCompanyIdRoute
  AppCompaniesNewRoute: typeof AppCompaniesNewRoute
  AppCompaniesIndexRoute: typeof AppCompaniesIndexRoute
  AppCompaniesCompanyIdEditRoute: typeof AppCompaniesCompanyIdEditRoute
}

const AppCompaniesRouteChildren: AppCompaniesRouteChildren = {
  AppCompaniesCompanyIdRoute: AppCompaniesCompanyIdRoute,
  AppCompaniesNewRoute: AppCompaniesNewRoute,
  AppCompaniesIndexRoute: AppCompaniesIndexRoute,
  AppCompaniesCompanyIdEditRoute: AppCompaniesCompanyIdEditRoute,
}

const AppCompaniesRouteWithChildren = AppCompaniesRoute._addFileChildren(
  AppCompaniesRouteChildren,
)

interface AppRouteChildren {
  AppAccountRoute: typeof AppAccountRoute
  AppCalculatorsRoute: typeof AppCalculatorsRouteWithChildren
  AppCompaniesRoute: typeof AppCompaniesRouteWithChildren
  AppDashboardRoute: typeof AppDashboardRoute
  AppHistoryRoute: typeof AppHistoryRoute
  AppClientsClientIdRoute: typeof AppClientsClientIdRoute
  AppClientsNewRoute: typeof AppClientsNewRoute
  AppClientsIndexRoute: typeof AppClientsIndexRoute
  AppClientsClientIdEditRoute: typeof AppClientsClientIdEditRoute
  AppClientsClientIdScenariosRoute: typeof AppClientsClientIdScenariosRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAccountRoute: AppAccountRoute,
  AppCalculatorsRoute: AppCalculatorsRouteWithChildren,
  AppCompaniesRoute: AppCompaniesRouteWithChildren,
  AppDashboardRoute: AppDashboardRoute,
  AppHistoryRoute: AppHistoryRoute,
  AppClientsClientIdRoute: AppClientsClientIdRoute,
  AppClientsNewRoute: AppClientsNewRoute,
  AppClientsIndexRoute: AppClientsIndexRoute,
  AppClientsClientIdEditRoute: AppClientsClientIdEditRoute,
  AppClientsClientIdScenariosRoute: AppClientsClientIdScenariosRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  SharedTokenRoute: SharedTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
