/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppCalculatorsRouteImport } from './routes/_app/calculators'
import { Route as AppAccountRouteImport } from './routes/_app/account'
import { Route as AppClientsIndexRouteImport } from './routes/_app/clients/index'
import { Route as AppClientsNewRouteImport } from './routes/_app/clients/new'
import { Route as AppClientsClientIdRouteImport } from './routes/_app/clients/$clientId'
import { Route as AppClientsClientIdEditRouteImport } from './routes/_app/clients/$clientId.edit'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCalculatorsRoute = AppCalculatorsRouteImport.update({
  id: '/calculators',
  path: '/calculators',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountRoute = AppAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AppRoute,
} as any)
const AppClientsIndexRoute = AppClientsIndexRouteImport.update({
  id: '/clients/',
  path: '/clients/',
  getParentRoute: () => AppRoute,
} as any)
const AppClientsNewRoute = AppClientsNewRouteImport.update({
  id: '/clients/new',
  path: '/clients/new',
  getParentRoute: () => AppRoute,
} as any)
const AppClientsClientIdRoute = AppClientsClientIdRouteImport.update({
  id: '/clients/$clientId',
  path: '/clients/$clientId',
  getParentRoute: () => AppRoute,
} as any)
const AppClientsClientIdEditRoute = AppClientsClientIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => AppClientsClientIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/account': typeof AppAccountRoute
  '/calculators': typeof AppCalculatorsRoute
  '/dashboard': typeof AppDashboardRoute
  '/clients/$clientId': typeof AppClientsClientIdRouteWithChildren
  '/clients/new': typeof AppClientsNewRoute
  '/clients/': typeof AppClientsIndexRoute
  '/clients/$clientId/edit': typeof AppClientsClientIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/account': typeof AppAccountRoute
  '/calculators': typeof AppCalculatorsRoute
  '/dashboard': typeof AppDashboardRoute
  '/clients/$clientId': typeof AppClientsClientIdRouteWithChildren
  '/clients/new': typeof AppClientsNewRoute
  '/clients': typeof AppClientsIndexRoute
  '/clients/$clientId/edit': typeof AppClientsClientIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/_app/account': typeof AppAccountRoute
  '/_app/calculators': typeof AppCalculatorsRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/clients/$clientId': typeof AppClientsClientIdRouteWithChildren
  '/_app/clients/new': typeof AppClientsNewRoute
  '/_app/clients/': typeof AppClientsIndexRoute
  '/_app/clients/$clientId/edit': typeof AppClientsClientIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/account'
    | '/calculators'
    | '/dashboard'
    | '/clients/$clientId'
    | '/clients/new'
    | '/clients/'
    | '/clients/$clientId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/account'
    | '/calculators'
    | '/dashboard'
    | '/clients/$clientId'
    | '/clients/new'
    | '/clients'
    | '/clients/$clientId/edit'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/auth'
    | '/_app/account'
    | '/_app/calculators'
    | '/_app/dashboard'
    | '/_app/clients/$clientId'
    | '/_app/clients/new'
    | '/_app/clients/'
    | '/_app/clients/$clientId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/calculators': {
      id: '/_app/calculators'
      path: '/calculators'
      fullPath: '/calculators'
      preLoaderRoute: typeof AppCalculatorsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/account': {
      id: '/_app/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AppAccountRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clients/': {
      id: '/_app/clients/'
      path: '/clients'
      fullPath: '/clients/'
      preLoaderRoute: typeof AppClientsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clients/new': {
      id: '/_app/clients/new'
      path: '/clients/new'
      fullPath: '/clients/new'
      preLoaderRoute: typeof AppClientsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clients/$clientId': {
      id: '/_app/clients/$clientId'
      path: '/clients/$clientId'
      fullPath: '/clients/$clientId'
      preLoaderRoute: typeof AppClientsClientIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clients/$clientId/edit': {
      id: '/_app/clients/$clientId/edit'
      path: '/edit'
      fullPath: '/clients/$clientId/edit'
      preLoaderRoute: typeof AppClientsClientIdEditRouteImport
      parentRoute: typeof AppClientsClientIdRoute
    }
  }
}

interface AppClientsClientIdRouteChildren {
  AppClientsClientIdEditRoute: typeof AppClientsClientIdEditRoute
}

const AppClientsClientIdRouteChildren: AppClientsClientIdRouteChildren = {
  AppClientsClientIdEditRoute: AppClientsClientIdEditRoute,
}

const AppClientsClientIdRouteWithChildren =
  AppClientsClientIdRoute._addFileChildren(AppClientsClientIdRouteChildren)

interface AppRouteChildren {
  AppAccountRoute: typeof AppAccountRoute
  AppCalculatorsRoute: typeof AppCalculatorsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppClientsClientIdRoute: typeof AppClientsClientIdRouteWithChildren
  AppClientsNewRoute: typeof AppClientsNewRoute
  AppClientsIndexRoute: typeof AppClientsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAccountRoute: AppAccountRoute,
  AppCalculatorsRoute: AppCalculatorsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppClientsClientIdRoute: AppClientsClientIdRouteWithChildren,
  AppClientsNewRoute: AppClientsNewRoute,
  AppClientsIndexRoute: AppClientsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
